### ISSUE TITLE
Project management smell or misunderstanding?

### ISSUE THREAD

**Issue by pgdr** [OPM/opm-data-legacy#293] opened 2017-12-18 13:01 UTC
I'm just asking here, because I don't really know, and I've been wondering for a long while.

Aren't all these `update the reference solutions for ...` changes a testing smell?

Is this documented in some best practice for testing anywhere or is it an OPM invention?

**Comment by akva2** [comment] 2017-12-18 13:06
please make sense, then i can answer.

**Comment by akva2** [comment] 2017-12-18 13:07
in general, it's generated by a opm-specific script which helps with automating regression data updates. but i don't understand your use of the word 'smell'.

**Comment by pgdr** [comment] 2017-12-18 13:11
Wikipedia is always a good starting point.

> According to Martin Fowler, "[a code smell](https://en.wikipedia.org/wiki/Code_smell) is a surface indication that usually corresponds to a deeper problem in the system".

The problem I'm having is that OPM is the only project I know of for which the integration tests or regression tests are changed at this frequency.

The question is whether this is a well-founded way to run a test suite, or if it's an OPM invention.  If so, what research* has gone into the benefits and shortcomings of this regime?

*thought

**Comment by andlaus** [comment] 2017-12-18 13:23
I think these PRs are a pain in the butt, but unfortunately they are currently required because the reference solutions are co-located with the input files in opm-data. Since input files and the reference solutions computed using a specific simulator are conceptually different IMO, it would make a lot of sense to have a  better approach of how to provide the reference solutions. Since this is a bit of work, I'm currently busy with more important stuff, I do not really know any "good" way to do it and I think this is more of a nuisance rather than a dealbreaker, I am not going to spend time on this in the near to medium term. that said, if you're annoyed by this, I guess nobody will object to patches for the unit/integration tests infrastructure which improve this situation @pgdr.

**Comment by akva2** [comment] 2017-12-18 13:25
it's a well founded way to run a test suite, it's done in variants of this in all code bases i work in. the reason for the frequent updates are as far as i see it, a combination of

1) bad choice of tests which exhibit instabilities
2) a code under construction
3) the fact that we do not directly control output data through tolerances due to unit and precision conversions between simulator data and output (no raw access).

however, frequent updates is really not an issue in itself. it just shows that the tests will capture any changes, small or big. which a human can then consider.

**Comment by andlaus** [comment] 2017-12-18 13:27
while relaxing the tolerances would help with @pgdr's annoyance, I guess that @alfbr has some quite strong thoughts about this.

**Comment by akva2** [comment] 2017-12-18 13:31
most of the troubles are due to different time stepping being triggered rather than tolerances. obviously those are indirectly coupled, but the real issue as far as being good test cases is that the sensitivity that allows for the different stepping history being triggered in the first place should ideally be nipped out.

**Comment by andlaus** [comment] 2017-12-18 13:44
hm, @totto82  proposed to only compare the summary files at report steps recently. I guess that's a good idea which would help here.

**Comment by akva2** [comment] 2017-12-18 14:26
yes that sounds like a good idea.

**Comment by alfbr** [comment] 2017-12-18 14:33
> while relaxing the tolerances would help with @pgdr's annoyance, I guess that @alfbr has some quite strong thoughts about this.

Yes I do :-) In this case relaxing tolerances quickly translates to silently accepting significant deviations in the solution in every pull request. This is a dangerous path.

> hm, @totto82 proposed to only compare the summary files at report steps recently.

I have to admit that I am sceptical, but let's discuss it. Generally speaking, I would like us to care more when time stepping changes, not less, but this may be catered to better by the performance testing we already have.

**Comment by pgdr** [comment] 2017-12-18 15:59
> relaxing tolerances quickly translates to silently accepting significant deviations in the solution in every pull request

@alfbr The problem is that we already do that today.  Let's say there have been 100 updates of test data.  Do we know why the results changed for each of them?  I looked up a couple at random and four of them were without actually changing code and one introduced a new keyword.  We should be explicit about which keyword we test for, and rather extend the _tests_ whenever we add keywords.

We should compare the values that we expect are correct, and if they change (and we need to update reference values) something is actually _wrong_.  Now we're just changing the reference values without any clear goal.

**Comment by alfbr** [comment] 2017-12-18 16:04
> Do we know why the results changed for each of them?

Actually, we typically do.

**Comment by andlaus** [comment] 2017-12-18 16:05
> We should compare the values that we expect are correct, and if they change (and we need to update reference values) something is actually wrong. Now we're just changing the reference values without any clear goal.

So you finally support my argument that no test is better than a pointless test? (I do not think that the opm-simulator tests are pointless, BTW.)

**Comment by alfbr** [comment] 2017-12-18 16:06
I am afraid this is bringing up an old discussion that have been less than constructive in the past. Closing.

**Closed as completed by alfbr** 2017-12-18 16:06 UTC

**Comment by joakim-hove** [comment] 2017-12-18 16:42
I saw @alfbr closing this, and I understand the reason, I just could not resist adding my two 0.02$ to the discussion. I will *not* add any further comments to this - unless explicitly asked to do so. Anyways:

As I see it the system for running integration tests and updating of test data works well; it is well maintained and supported and the amount of work on the developers is quite limited. The test framework certainly works as a well tuned n-point seatbelt and I am certain it has caught many bugs. Nevertheless @pgdr initial posting made me think - and I do agree with this:

> We should compare the values that we expect are correct, and if they change (and we need to update reference values) something is actually wrong. Now we're just changing the reference values without any clear goal.

My analogy is that the current suite of integration tests are in the driver seat, with developers updating test data left and right to stay on the bandwagon. The current integration tests provide a very good safety harness, but they do not provide the benefits of more unit tests in each repository. A richer selection of unit tests in each repository would give:

1. Better code - **testable code is better**. If it is painful/difficult to test your code that is a clear sign of bad design, typically layering violations, too strong couplings and state changes.

2. If you have made changes in e.g. opm-grid it is a bit late to discover your errors when the integrations tests in opm-simulators, a couple of repos down the line, fail.

So anyway - now when the opm community has an extensive framework in place for integration testing I would encourage more focus on unit tests in the various repositories.

Happy testing!

**Comment by atgeirr** [comment] 2017-12-20 14:28
I'll also take the liberty to comment on the closed issue... The annoyingly frequent updates usually have fairly well understood explanations, as others have said.

However for the particular case of the time-stepping instability of the SPE3 and SPE5 cases, I wish I had a better understanding of why it happens. Until we have understood that fully, changing the testing to ignore such changes may not be the best course of action.
